<!-- background image loaded with the same id as amin image -->
<div class="bodyImg" id="bodyImg">
</div>

<div class="container-index">
  <h1 class="text-center">Random'Art</h1>
  <div class="container-img">
    <a href="" id="imageId">
      <!-- main image randomly loaded -->
      <img id="imageRandom" src="" alt="randomImage" class="img-responsive">
    </a>
  </div>
  <div>
  <p class="clickMe">Click picture to see details</p>
  <p class="next" id="next">next!</p>
  </div>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="js/randomImage.js"></script>
<script src="js/addComment.js"></script>
