<div class="bodyImg" id="bodyImg">
  <!-- random background image -->
</div>

<div class="login-form">
  <h2>LOGIN</h2>
  <form action="login.php" method="post">
    <input type="text" id="email" name="email" placeholder="Email">
    <input type="password" id="password" name="password" placeholder="Password">
    <button type="submit">Login</button>
    <a class="cancel-button" href="index.php">Cancel</a>
    <!-- error message mail or passeword -->
    <p><?= $message ?></p>
  </form>
</div>




