<div class="bodyImg" id="bodyImg">
    <!-- random background image -->
</div>

<div class="register-form">
    <h2>REGISTER</h2>
    <form action="register.php" method="post">
        <input type="text" class="firstName" id="firstName" name="firstName" placeholder="First Name">
        <input type="text" class="lastName" id="lastName" name="lastName" placeholder="Last Name">
        <input type="text" class="pseudo" id="pseudo" name="pseudo" placeholder="Pseudo">
        <input type="email" class="email" id="email" name="email" placeholder="Email">
        <input type="password" class="password" id="password" name="password" placeholder="Password">
        <button type="submit" name="submit" value="submit">Register</button>
        <a class="cancel-button" href="index.php">Cancel</a>
    </form>
</div>





