
<div class="bodyImg" id="bodyImg">
  <!-- ramdomly loaded image -->
</div>

<div class="container-upload">
  <h2>Upload</h2>
  <form action="upload.php" method="post" enctype="multipart/form-data">
    <div class="upload">
      <label for="image">Select pictures (JPG, JPEG, PNG)</label>
      <input type="file" class="imageUpload" id="imageUpload" name="imageUpload" accept=".jpg, .jpeg, .png" multiple>
    </div>
    <div>
      <button>Upload</button>
      <a class="cancel-button" href="index.php">Cancel</a>
    </div>
  </form>
</div>

